- apps/ailab-shared/base/ubuntu-deployment.yaml
> issue 42 deploy webtop c

- apps/ailab-shared/argo-app.yaml
ref #42 
add namespace definition for ailab-shared in argo-app.yaml
> 42 deploy webtop e

- apps/ailab-shared/base/ubuntu-deployment-jsantos.yaml
ref #42 
replace ailab-shared deployment with ubuntu-jsantos deployment and service configuration
> 42 deploy webtop f 😩

- apps/ailab-shared/base/ubuntu-deployment-jsantos.yaml
> 42 deploy webtop prevent container termination

- apps/ailab-shared/base/ubuntu-deployment-jsantos.yaml
update ubuntu deployment to use command and args syntax for entrypoint
> 42 deploy webtop h

- apps/webtop/base/jsantos-webtop-ingress.yaml
- apps/webtop/base/jsantos-webtop-secrets.yaml
> Issue 42 deploy webtop j

- apps/webtop/base/jsantos-webtop-deployment.yaml
> Issue 42 Deploy webtop m

- apps/fertiscan-preview/base/backend-deployment.yaml
- apps/fertiscan-preview/base/frontend-deployment.yaml
> issue #59: deploy fertiscan-preview frontend 479 & backend 248

- storage/cloudnativepg/base/acia-cfia-dev-cluster/cluster.yaml
- storage/cloudnativepg/base/acia-cfia-dev-cluster/secrets.yaml
- storage/minio/argo-app.yaml
- storage/minio/base/minio-secret.yaml
- storage/minio/helm/values.yaml
- storage/minio/kustomization.yaml
> issue #61: minio deployment + backup configuration

- .gitignore
- storage/cloudnativepg/base/database/nachet-dev.yaml
- storage/cloudnativepg/base/database/nachet-prod.yaml
- storage/cloudnativepg/base/kustomization.yaml
- storage/cloudnativepg/base/nachet-dev-cluster/backup.yaml
- storage/cloudnativepg/base/nachet-dev-cluster/cluster.yaml
- storage/cloudnativepg/base/nachet-dev-cluster/secrets.yaml
- storage/cloudnativepg/base/nachet-prod-cluster/backup.yaml
- storage/cloudnativepg/base/nachet-prod-cluster/cluster.yaml
- storage/cloudnativepg/base/nachet-prod-cluster/secrets.yaml
> 74 machet cloud native pg

- storage/cloudnativepg/base/nachet-dev-cluster/cluster.yaml
- storage/cloudnativepg/base/nachet-prod-cluster/cluster.yaml
> Issue 76 Fix Nachet DB deployment

- apps/nachet-dev/argo-app.yaml
- apps/nachet-dev/base/ingress.yaml
- apps/nachet-dev/base/landing-403-nachet.yaml
- apps/nachet-dev/base/nachet-backend-deployment.yml
- apps/nachet-dev/base/nachet-blob-storage-mock.yml
- apps/nachet-dev/base/nachet-frontend-deployment.yml
- apps/nachet-dev/base/nachet-rcnn-model-deployment.yaml
- apps/nachet-dev/base/nachet-swin-22-spp-model-deployment.yaml
- apps/nachet-dev/base/nachet-swin-27-spp-model-deployment.yaml
- apps/nachet-dev/base/nachet-swin-model-deployment.yaml
- apps/nachet-dev/base/secrets.yaml
- apps/nachet-dev/kustomization.yaml
closes #79 
closes #80 
closes #83 
closes #84
> 79 80 deploy nachet models azurite

- apps/nachet-dev/base/ingress.yaml
- apps/nachet-dev/base/nachet-backend-deployment.yml
- apps/nachet-dev/base/nachet-blob-storage-mock.yml
- apps/nachet-dev/base/nachet-frontend-deployment.yml
- apps/nachet-dev/base/nachet-rcnn-model-deployment.yaml
- apps/nachet-dev/base/nachet-swin-22-spp-model-deployment.yaml
- apps/nachet-dev/base/nachet-swin-27-spp-model-deployment.yaml
- apps/nachet-dev/base/nachet-swin-model-deployment.yaml
- apps/nachet-prod/argo-app.yaml
- apps/nachet-prod/base/ingress.yaml
- apps/nachet-prod/base/nachet-backend-deployment.yml
- apps/nachet-prod/base/nachet-blob-storage-mock.yml
- apps/nachet-prod/base/nachet-frontend-deployment.yml
- apps/nachet-prod/base/nachet-rcnn-model-deployment.yaml
- apps/nachet-prod/base/nachet-swin-22-spp-model-deployment.yaml
- apps/nachet-prod/base/nachet-swin-27-spp-model-deployment.yaml
- apps/nachet-prod/base/nachet-swin-model-deployment.yaml
- apps/nachet-prod/base/secrets.yaml
- apps/nachet-prod/kustomization.yaml
- gitops/argocd-apps/kustomization.yaml
> Issue 73 deploy nachet prod

- apps/ailab-shared/argo-app.yaml
- apps/ailab-shared/base/alpine.yaml
- apps/ailab-shared/base/sharedpvc.yaml
- gitops/argocd-apps/kustomization.yaml
> Issue 88 create shared filesystem

- apps/webtop/base/jsantos-webtop-deployment.yaml
- apps/webtop/base/jsantos-webtop-ingress.yaml
- apps/webtop/base/sharedpv.yaml
- gitops/argocd-apps/kustomization.yaml
> Issue 88 Deploy webtop

- apps/nachet-dev/base/ingress.yaml
- apps/nachet-dev/base/nachet-rcnn-model-deployment.yaml
- apps/nachet-dev/base/nachet-swin-27-spp-model-deployment.yaml
> Issue 89 deploy nachet azurite ingress

- apps/nachet-dev/base/nachet-backend-deployment.yml
> Issue 106 Deploy Nachet allow string list CORS

- apps/louis/base/litellm/configmap.yaml
- apps/louis/base/litellm/deployment.yaml
- apps/louis/base/litellm/ingress.yaml
- apps/louis/base/litellm/secrets.yaml
- apps/louis/base/ollama/deployment.yaml
- apps/louis/base/openwebui/deployment.yaml
- apps/louis/base/openwebui/secrets.yaml
closes #110 
Based on current LiteLLM documentation https://docs.litellm.ai/docs/proxy/deploy#kubernetes
> Issue 110 LiteLLM configmap

- apps/louis/base/kustomization.yaml
- apps/louis/base/litellm/deployment.yaml
- apps/louis/base/litellm/secrets.yaml
- apps/louis/base/openwebui/configmap.yaml
- apps/louis/base/openwebui/deployment.yaml
- apps/louis/base/openwebui/secrets.yaml
- storage/cloudnativepg/base/acia-cfia-dev-cluster/cluster.yaml
- storage/cloudnativepg/base/acia-cfia-dev-cluster/secrets.yaml
- storage/cloudnativepg/base/database/litellm.yaml
- storage/cloudnativepg/base/database/openwebui.yaml
- storage/cloudnativepg/base/kustomization.yaml
> Issue 115 openwebui configmap

- apps/nachet-dev/base/certificates.yaml
- apps/nachet-dev/base/ingress.yaml
> Issue 124 self signed certs nachet stack

- gitops/argocd-apps/kustomization.yaml
- infrastructure/crossplane/argo-app.yaml
- infrastructure/crossplane/helm/values.yaml
- infrastructure/crossplane/kustomization.yaml
> crossplane deployment

- apps/nachet-dev/base/nachet-backend-deployment.yml
- apps/nachet-dev/base/secrets.yaml
> Issue 128 split nachet config secrets

- apps/louis/base/gptresearcher/certificates.yaml
- apps/louis/base/gptresearcher/configmap.yaml
- apps/louis/base/gptresearcher/deployment.yaml
- apps/louis/base/gptresearcher/secrets.yaml
- apps/louis/base/kustomization.yaml
- apps/louis/base/litellm/configmap.yaml
- apps/louis/base/mcp-bridge/deployment.yaml
- apps/louis/base/mcp-bridge/secrets.yaml
- apps/louis/base/openwebui/certificates.yaml
- apps/louis/base/openwebui/ingress.yaml
> Issue 133 louis gpt researcher mcp

- apps/gpt-researcher/argo-app.yaml
- gitops/argocd/base/argocd-notifications-cm.yaml
- gitops/argocd/base/secret.yaml
> issue #93: argocd-notification github

- gitops/argocd-apps/kustomization.yaml
- mlops/mlflow/argo-app.yaml
- mlops/mlflow/base/secret.yaml
- mlops/mlflow/helm/values.yaml
- mlops/mlflow/kustomization.yaml
- storage/cloudnativepg/base/acia-cfia-dev-cluster/cluster.yaml
- storage/cloudnativepg/base/acia-cfia-dev-cluster/secrets.yaml
- storage/cloudnativepg/base/database/mlflow.yaml
- storage/cloudnativepg/base/kustomization.yaml
> issue #28: mlflow deployment

- apps/annotation/argo-app.yaml
- apps/annotation/base/gateway.yaml
- apps/annotation/base/httproute.yaml
- apps/annotation/base/kustomization.yaml
- apps/annotation/base/labelstudio/certificates.yaml
- apps/annotation/base/labelstudio/labelstudio.yaml
- apps/annotation/base/labelstudio/pvcs.yaml
- apps/annotation/base/labelstudio/secrets.yaml
- apps/annotation/kustomization.yaml
- storage/cloudnativepg/base/acia-cfia-dev-cluster/cluster.yaml
- storage/cloudnativepg/base/acia-cfia-dev-cluster/secrets.yaml
- storage/cloudnativepg/base/database/labelstudio.yaml
closes #199 
Deploy Label Studio for image annotation
https://github.com/HumanSignal/label-studio
https://labelstud.io/guide/get_started
> Issue #199 Deploy Label Studio

- README.md
- apps/nachet-dev/base/certificates.yaml
- apps/nachet-dev/base/gateway.yaml
- apps/nachet-dev/base/httproute.yaml
- apps/nachet-dev/base/kustomization.yaml
- apps/nachet-dev/base/nachet-dev-op-deployment.yml
- apps/nachet-dev/base/secrets.yaml
closes #332
closes ai-cfia/nachet#236
> Issue 332 nachet dev monorepo
